<?php

use Illuminate\Database\Seeder;

class sss_table extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sss_table')->insert(array(
            array(
              'low_compensation' => 'BELOW',
              'high_compensation' => '2250',
              'monthly_salary_detail' => '2000',
              'ss_er' => '160',
              'ss_ee' => '80',
              'sss_total' => '240',
              'ec_er' => '10',
              'tc_er' => '170',
              'tc_ee' => '80',
              'tc_total' => '250',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '2250',
              'high_compensation' => ' 2749.99',
              'monthly_salary_detail' => '2500',
              'ss_er' => '200',
              'ss_ee' => '100',
              'sss_total' => '300',
              'ec_er' => '10',
              'tc_er' => '210',
              'tc_ee' => '100',
              'tc_total' => '310',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '2750',
              'high_compensation' => '3249.99',
              'monthly_salary_detail' => '3000',
              'ss_er' => '240',
              'ss_ee' => '120',
              'sss_total' => '360',
              'ec_er' => '10',
              'tc_er' => '250',
              'tc_ee' => '120',
              'tc_total' => '370',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '3250',
              'high_compensation' => '3749.99',
              'monthly_salary_detail' => '3500',
              'ss_er' => '280',
              'ss_ee' => '140',
              'sss_total' => '420',
              'ec_er' => '10',
              'tc_er' => '290',
              'tc_ee' => '140',
              'tc_total' => '430',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '3750',
              'high_compensation' => '4249.99',
              'monthly_salary_detail' => '4000',
              'ss_er' => '320.00',
              'ss_ee' => '160.00',
              'sss_total' => '480',
              'ec_er' => '10',
              'tc_er' => '330',
              'tc_ee' => '160',
              'tc_total' => '490',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '4250',
              'high_compensation' => '4749.99',
              'monthly_salary_detail' => '4500',
              'ss_er' => '360',
              'ss_ee' => '180',
              'sss_total' => '540',
              'ec_er' => '10',
              'tc_er' => '370',
              'tc_ee' => '180',
              'tc_total' => '550',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '4750',
              'high_compensation' => '5249.99',
              'monthly_salary_detail' => '5000',
              'ss_er' => '400',
              'ss_ee' => '200',
              'sss_total' => '600',
              'ec_er' => '10',
              'tc_er' => '410',
              'tc_ee' => '200',
              'tc_total' => '610',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '5250',
              'high_compensation' => '5749.99',
              'monthly_salary_detail' => '5500',
              'ss_er' => '440',
              'ss_ee' => '220',
              'sss_total' => '660',
              'ec_er' => '10',
              'tc_er' => '450',
              'tc_ee' => '220',
              'tc_total' => '670',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '5750',
              'high_compensation' => '6249.99',
              'monthly_salary_detail' => '6000',
              'ss_er' => '480',
              'ss_ee' => '240',
              'sss_total' => '720',
              'ec_er' => '10',
              'tc_er' => '490',
              'tc_ee' => '240',
              'tc_total' => '730',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '6250',
              'high_compensation' => '6749.99',
              'monthly_salary_detail' => '6500',
              'ss_er' => '520',
              'ss_ee' => '260',
              'sss_total' => '780',
              'ec_er' => '10',
              'tc_er' => '530',
              'tc_ee' => '260',
              'tc_total' => '790',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '6750',
              'high_compensation' => '7249.99',
              'monthly_salary_detail' => '7000',
              'ss_er' => '560',
              'ss_ee' => '280',
              'sss_total' => '840',
              'ec_er' => '10',
              'tc_er' => '570',
              'tc_ee' => '280',
              'tc_total' => '850',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '7250',
              'high_compensation' => '7749.99',
              'monthly_salary_detail' => '7500',
              'ss_er' => '600',
              'ss_ee' => '300',
              'sss_total' => '900',
              'ec_er' => '10',
              'tc_er' => '610',
              'tc_ee' => '300',
              'tc_total' => '910',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '7750',
              'high_compensation' => '8249.99',
              'monthly_salary_detail' => '8000',
              'ss_er' => '640',
              'ss_ee' => '320',
              'sss_total' => '960',
              'ec_er' => '10',
              'tc_er' => '650',
              'tc_ee' => '320',
              'tc_total' => '970',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '8250',
              'high_compensation' => '8749.99',
              'monthly_salary_detail' => '8500',
              'ss_er' => '680',
              'ss_ee' => '340',
              'sss_total' => '1020',
              'ec_er' => '10',
              'tc_er' => '690',
              'tc_ee' => '340',
              'tc_total' => '1030',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '8750',
              'high_compensation' => '9249.99',
              'monthly_salary_detail' => '9000',
              'ss_er' => '720',
              'ss_ee' => '360',
              'sss_total' => '1080',
              'ec_er' => '10',
              'tc_er' => '730',
              'tc_ee' => '360',
              'tc_total' => '1090',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '9250',
              'high_compensation' => '9749.99',
              'monthly_salary_detail' => '9500',
              'ss_er' => '760',
              'ss_ee' => '380',
              'sss_total' => '1140',
              'ec_er' => '10',
              'tc_er' => '770',
              'tc_ee' => '380',
              'tc_total' => '1150',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '9750',
              'high_compensation' => '10249.99',
              'monthly_salary_detail' => '10000',
              'ss_er' => '800',
              'ss_ee' => '400',
              'sss_total' => '1200',
              'ec_er' => '10',
              'tc_er' => '810',
              'tc_ee' => '400',
              'tc_total' => '1210',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '10250',
              'high_compensation' => '10749.99',
              'monthly_salary_detail' => '10500',
              'ss_er' => '840',
              'ss_ee' => '420',
              'sss_total' => '1260',
              'ec_er' => '10',
              'tc_er' => '850',
              'tc_ee' => '420',
              'tc_total' => '1270',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '10760',
              'high_compensation' => '11249.99',
              'monthly_salary_detail' => '11000',
              'ss_er' => '880',
              'ss_ee' => '440',
              'sss_total' => '1320',
              'ec_er' => '10',
              'tc_er' => '890',
              'tc_ee' => '440',
              'tc_total' => '1330',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '11250',
              'high_compensation' => '11749.99',
              'monthly_salary_detail' => '11500',
              'ss_er' => '920',
              'ss_ee' => '460',
              'sss_total' => '1380',
              'ec_er' => '10',
              'tc_er' => '930',
              'tc_ee' => '460',
              'tc_total' => '1390',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '11750',
              'high_compensation' => '12249.99',
              'monthly_salary_detail' => '12000',
              'ss_er' => '960',
              'ss_ee' => '480',
              'sss_total' => '1440',
              'ec_er' => '10',
              'tc_er' => '970',
              'tc_ee' => '480',
              'tc_total' => '1450',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '12250',
              'high_compensation' => '12749.99',
              'monthly_salary_detail' => '12500',
              'ss_er' => '1000',
              'ss_ee' => '500',
              'sss_total' => '1500',
              'ec_er' => '10',
              'tc_er' => '1010',
              'tc_ee' => '500',
              'tc_total' => '1510',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '12750',
              'high_compensation' => '13249.99',
              'monthly_salary_detail' => '13000',
              'ss_er' => '1040',
              'ss_ee' => '520',
              'sss_total' => '1560',
              'ec_er' => '10',
              'tc_er' => '1050',
              'tc_ee' => '520',
              'tc_total' => '1570',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '13250',
              'high_compensation' => '13749.99',
              'monthly_salary_detail' => '13500',
              'ss_er' => '1080',
              'ss_ee' => '540',
              'sss_total' => '1620',
              'ec_er' => '10',
              'tc_er' => '1090',
              'tc_ee' => '540',
              'tc_total' => '1630',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '13750',
              'high_compensation' => '14249.99',
              'monthly_salary_detail' => '14000',
              'ss_er' => '1120',
              'ss_ee' => '560',
              'sss_total' => '1680',
              'ec_er' => '10',
              'tc_er' => '1130',
              'tc_ee' => '560',
              'tc_total' => '1690' ,
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '14250',
              'high_compensation' => '14749.99',
              'monthly_salary_detail' => '14500',
              'ss_er' => '1160',
              'ss_ee' => '580',
              'sss_total' => '1740',
              'ec_er' => '10',
              'tc_er' => '1170',
              'tc_ee' => '580',
              'tc_total' => '1750',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '14750',
              'high_compensation' => '15249.99',
              'monthly_salary_detail' => '15000',
              'ss_er' => '1200',
              'ss_ee' => '600',
              'sss_total' => '1800',
              'ec_er' => '30',
              'tc_er' => '1230',
              'tc_ee' => '600',
              'tc_total' => '1830',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '15250',
              'high_compensation' => '15749.99',
              'monthly_salary_detail' => '15500',
              'ss_er' => '1240',
              'ss_ee' => '620',
              'sss_total' => '1860',
              'ec_er' => '30',
              'tc_er' => '1270',
              'tc_ee' => '620',
              'tc_total' => '1890',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '15750',
              'high_compensation' => '16249.99',
              'monthly_salary_detail' => '16000' ,
              'ss_er' => '1280',
              'ss_ee' => '640',
              'sss_total' => '1920',
              'ec_er' => '30',
              'tc_er' => '1310',
              'tc_ee' => '640',
              'tc_total' => '1950' ,
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '16250',
              'high_compensation' => '16749.99',
              'monthly_salary_detail' => '16500',
              'ss_er' => '1320',
              'ss_ee' => '660',
              'sss_total' => '1980',
              'ec_er' => '30',
              'tc_er' => '1350',
              'tc_ee' => '660',
              'tc_total' => '2010',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '16750',
              'high_compensation' => '17249.99',
              'monthly_salary_detail' => '17000',
              'ss_er' => '1360',
              'ss_ee' => '680',
              'sss_total' => '2040',
              'ec_er' => '30',
              'tc_er' => '1390',
              'tc_ee' => '680',
              'tc_total' => '2070',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '17250',
              'high_compensation' => '17749.99',
              'monthly_salary_detail' => '17500',
              'ss_er' => '1400',
              'ss_ee' => '700',
              'sss_total' => '2100',
              'ec_er' => '30',
              'tc_er' => '1430',
              'tc_ee' => '700',
              'tc_total' => '2130',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '17750',
              'high_compensation' => '18249.99',
              'monthly_salary_detail' => '18000',
              'ss_er' => '1440',
              'ss_ee' => '720',
              'sss_total' => '2160',
              'ec_er' => '30',
              'tc_er' => '1470',
              'tc_ee' => '720',
              'tc_total' => '2190',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '18250',
              'high_compensation' => '18749.99',
              'monthly_salary_detail' => '18500',
              'ss_er' => '1480',
              'ss_ee' => '740',
              'sss_total' => '2220',
              'ec_er' => '30',
              'tc_er' => '1510',
              'tc_ee' => '740',
              'tc_total' => '2250',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '18750',
              'high_compensation' => '19249.99',
              'monthly_salary_detail' => '19000',
              'ss_er' => '1520',
              'ss_ee' => '760',
              'sss_total' => '2280',
              'ec_er' => '30',
              'tc_er' => '1550',
              'tc_ee' => '760',
              'tc_total' => '2310',
              'month' => 'April',
              'year' => '2019',
            ),
             array(
              'low_compensation' => '19250',
              'high_compensation' => '19749.99',
              'monthly_salary_detail' => '19500',
              'ss_er' => '1560',
              'ss_ee' => '780',
              'sss_total' => '2340',
              'ec_er' => '30',
              'tc_er' => '1590',
              'tc_ee' => '780',
              'tc_total' => '2370',
              'month' => 'April',
              'year' => '2019',
            ),

             array(
              'low_compensation' => '19750',
              'high_compensation' => 'ABOVE',
              'monthly_salary_detail' => '20000',
              'ss_er' => '1600',
              'ss_ee' => '800',
              'sss_total' => '2400',
              'ec_er' => '30',
              'tc_er' => '1630',
              'tc_ee' => '800',
              'tc_total' => '2430',
              'month' => 'April',
              'year' => '2019',
            ),
             ));
    }
}
